divyanshu-rawat/Awesome-JS

- Repeat_String.js
Hi I have solved a bug I want you to merge it !!!
> solved a bug !

- BubbleSort
> Bubble Sort Algorithm

- primefactors.js
Hi,
The algorithm lists all the prime factors of a number.
Please review and let me know if any changes are required. (Issue #3)
Thanks
> All Prime Factors of Number

- shuffleArray.js
Function to shuffle a array at random.
> Added shuffel array function

- selectionSort.js
> init selectionSort.js

- linearSearch.js
> init linearSearch.js

- validate-us-telephone-numbers.js
added solution to "Validate US Telephone Numbers" advanced algorithm challenge
> Advanced Algorithm Solution: "Validate US Telephone Numbers"

- find-the-longest-word-in-a-string.js
- written in ES6
- provides solution with explanation
> adds solution for findLongestWord

- 3-palindromes.js
My solution for the third challenge: "Palindrome"
> 3 - Palidromes

- 2-factorialize.js
My solution for the second challenge: "Factorialize"
> 2 - Factorialize

- 1-reverse-string.js
My solution for the first challenge: "Reverse a String"
> 1 - Reverse string

- sleep-sort.js
Hi,
Funny one but this should be here imho.  
Thanks,
G.
---
Fixes #3
> Sleep Sort

- 7-ending.js
My solution for the seventh challenge: "Confirm the ending"
> 7 - ending

- 6-largest-of-four.js
My solution for the sixth challenge: "Largest of four"
> 6 - Largest of four

- 5-title-case.js
My solution for the fifth challenge: "Title case"
> 5 - Title case

- 4-max-length.js
My solution for the fourth challenge: "Max length"
> 4 - Max length

- SelectionSort.js
Test the code here - https://jsfiddle.net/IshamMohamed/8q9c3ycu/
> Added Selection Sort

- selectrion-sort.js
Add Selection Sort and Insertion Sort Algorithm #3
> Selection sort

- pairwise2.js
> Solution to pairwise challenge

- array_intersect.js
> Added an example demonstrating array intersection

- README.md
> Updated Readme to include coding standards

- permutation.js
> Solution to No Repeat Please challenge (Recursion)

- add-together.js
> Solution to Add Together challenge

- qLearning.js
For [Issue 4](https://github.com/divyanshu-rawat/Basic-JS-Algorithms/issues/47)
[Q Learning](https://en.wikipedia.org/wiki/Q-learning) is a model-free [reinforcement learning](https://en.wikipedia.org/wiki/Reinforcement_learning) algorithm.
This code used a simple command line game to evaluate the result.
Goal of game: Move '0' from left to right.
Actions of game: 'LEFT' & 'RIGHT'
Solved : About 9 to 10 episode.
> Add Q Learning (A basic algorithm of reinforcement learning)

- longestWord.js
> longest word

- sort/quicksort.js
Added indentations and Durstenfeld shuffle algorithm for better performance
> Added indentations and Durstenfeld shuffle algorithm for better performance

- data-structures/queue.js
Added support for Queue Data Structure
> Added support for Queue Data Structure

- data-structures/minheap.js
Added support for Min Heap Data Structure
> Added support for Min Heap Data Structure

- data-structures/maxheap.js
Added support for Max Heap Data Structure.
> Added Max Heap Data Structure

- sort/selectionSort.js
Modified existing code segmenet to include proper indentations and documentations.
> Added indentation and documentation for Selection Sort code

- filterObjectKeys.js
- findObject.js
PR - Adding findObject generic function (...obj, ...predicate)
> findObject function

- regexUtils.js
Utility Function to check below REGEX options
1. Check for valid **EMAIL** address
2. Check for valid **URL** address
> Regex Utility Function

- search/dijkstrasAlgorithm.js
Classic search algorithm in javascript
> Create dijkstrasAlgorithm.js #86

- html/html-get-links.js
Function for getting all links in the current HTML and save it in an array.
> Added snippet for getting all links in an HTML

- ginit/.gitignore
- ginit/README.md
- ginit/index.js
- ginit/lib/files.js
- ginit/lib/github.js
- ginit/lib/inquirer.js
- ginit/lib/repo.js
- ginit/package-lock.json
- ginit/package.json
#92 contribution node.js
Terminal based cli for github
ginit
> Added github cli

- README.md
I have added some more coding standard what we follow in development.
> added coding standards to readme

- validator.js
> feat(Validator): Add email validation checker
